base:
  project: telecomChurn
  random_state: 999
  target_col: churn

data_source:
  s3_source: data_given/telecom_churn_data.csv
  

load_data:
  raw_dataset_csv: data/raw/telecom_churn_data.csv

split_data:
  train_path: data/processed/train.csv
  test_path: data/processed/test.csv
  test_size: 0.25

model_dir: saved_models

reports:
  scores: report/scores.json
  roc: report/roc.json
  prc: report/prc.json
  auc: report/auc.json
